server:
  port: 8888

spring:
  application:
    name: Config_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MatiasValdiviesoUisrael/tarea5
          clone-on-start: true
          search-paths: '{profile}'
  profiles:
    active: prod

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
